version: "3.9"
services:  
  frontend:
    container_name: Twitter-analysis-FE
    build: ./TwitterAnalysis-FE
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /app/node_modules
      - ./TwitterAnalysis-FE:/app
    ports:
      - "3000:3000"

  backend:
    container_name: Twitter-analysis-BE
    build: ./nodeBackEnd
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONNECTION_STRING: postgres://postgres:postgres@host.docker.internal:5432/testdb
      PORT: 3001
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /backend/node_modules
      - ./nodeBackEnd:/backend
    ports: 
      - 3001:3001
      - 9229:9229

  postgres:
    image: postgres:10.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - .:/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

